const POSTER_BASE_URL = import.meta.env.VITE_BASE_POSTER_URL;
const NETLIFY_FUNCTIONS_BASE_URL = import.meta.env
  .VITE_NETLIFY_FUNCTIONS_BASE_URL;

export { POSTER_BASE_URL, NETLIFY_FUNCTIONS_BASE_URL };
